Search.appendIndex(
    [
                {
            "fqsen": "\\Indigo\\Design\\Blocks\\testcard\u0028\u0029",
            "name": "testcard",
            "summary": "",
            "url": "namespaces/indigo-design-blocks.html#function_testcard"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\view",
            "name": "view",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-view.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\dropdown",
            "name": "dropdown",
            "summary": "A\u0020navigation\u0020box\u0020with\u0020drop\u0020down\u0020capabilities\u0020for\u0020anchors.",
            "url": "classes/Indigo-Design-Blocks-dropdown.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\dropdown\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-dropdown.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\footer",
            "name": "footer",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-footer.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\footer\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-footer.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\imageframe",
            "name": "imageframe",
            "summary": "Displays\u0020an\u0020image\u0020in\u0020a\u0020frame.",
            "url": "classes/Indigo-Design-Blocks-imageframe.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\imageframe\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-imageframe.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\infobox_filter_links\u0028\u0029",
            "name": "infobox_filter_links",
            "summary": "Decorates\u0020links\u0020with\u0020icons,\u0020used\u0020by\u0020infobox.",
            "url": "namespaces/indigo-design-blocks.html#function_infobox_filter_links"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\infobox",
            "name": "infobox",
            "summary": "A\u0020box\u0020that\u0020displays\u0020various\u0020types\u0020of\u0020information\u0020gleaned\u0020from\u0020one\u0020of\u0020the\nfollowing\u0020data\u0020sources\u003A\u0020rss.",
            "url": "classes/Indigo-Design-Blocks-infobox.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\infobox\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-infobox.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\tabs",
            "name": "tabs",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-tabs.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks\\tabs\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Blocks-tabs.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\testcard\u0028\u0029",
            "name": "testcard",
            "summary": "",
            "url": "namespaces/indigo-design-fancy.html#function_testcard"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\view",
            "name": "view",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-view.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\view\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-view.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\aside",
            "name": "aside",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-aside.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\aside\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-aside.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\footer",
            "name": "footer",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-footer.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\footer\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-footer.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\header",
            "name": "header",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-header.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\header\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-header.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\nav",
            "name": "nav",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-nav.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy\\nav\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Fancy-nav.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Gradient\\testcard\u0028\u0029",
            "name": "testcard",
            "summary": "",
            "url": "namespaces/indigo-design-gradient.html#function_testcard"
        },                {
            "fqsen": "\\Indigo\\Design\\Gradient\\view",
            "name": "view",
            "summary": "",
            "url": "classes/Indigo-Design-Gradient-view.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Gradient\\navigation",
            "name": "navigation",
            "summary": "",
            "url": "classes/Indigo-Design-Gradient-navigation.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Gradient\\navigation\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Gradient-navigation.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\testcard\u0028\u0029",
            "name": "testcard",
            "summary": "",
            "url": "namespaces/indigo-design-minimal.html#function_testcard"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\view",
            "name": "view",
            "summary": "",
            "url": "classes/Indigo-Design-Minimal-view.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\view\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Minimal-view.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\footer",
            "name": "footer",
            "summary": "",
            "url": "classes/Indigo-Design-Minimal-footer.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\footer\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Minimal-footer.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\navigation",
            "name": "navigation",
            "summary": "The\u0020navigation\u0020\u002D\u0020use\u0020only\u0020in\u0020conjunction\u0020with\u0020footer\u0021",
            "url": "classes/Indigo-Design-Minimal-navigation.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal\\navigation\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Minimal-navigation.html#method__render"
        },                {
            "fqsen": "\\Indigo\\Design\\Mobile\\testcard\u0028\u0029",
            "name": "testcard",
            "summary": "",
            "url": "namespaces/indigo-design-mobile.html#function_testcard"
        },                {
            "fqsen": "\\Indigo\\Design\\Mobile\\view",
            "name": "view",
            "summary": "",
            "url": "classes/Indigo-Design-Mobile-view.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Mobile\\navigation",
            "name": "navigation",
            "summary": "",
            "url": "classes/Indigo-Design-Mobile-navigation.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Mobile\\navigation\u003A\u003A_render\u0028\u0029",
            "name": "_render",
            "summary": "",
            "url": "classes/Indigo-Design-Mobile-navigation.html#method__render"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Blocks",
            "name": "Blocks",
            "summary": "",
            "url": "namespaces/indigo-design-blocks.html"
        },                {
            "fqsen": "\\Indigo\\Design",
            "name": "Design",
            "summary": "",
            "url": "namespaces/indigo-design.html"
        },                {
            "fqsen": "\\Indigo",
            "name": "Indigo",
            "summary": "",
            "url": "namespaces/indigo.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Fancy",
            "name": "Fancy",
            "summary": "",
            "url": "namespaces/indigo-design-fancy.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Gradient",
            "name": "Gradient",
            "summary": "",
            "url": "namespaces/indigo-design-gradient.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Minimal",
            "name": "Minimal",
            "summary": "",
            "url": "namespaces/indigo-design-minimal.html"
        },                {
            "fqsen": "\\Indigo\\Design\\Mobile",
            "name": "Mobile",
            "summary": "",
            "url": "namespaces/indigo-design-mobile.html"
        }            ]
);
